class MyStrings {

  List mistakes=[
    "Dikkat Eksikliği","Bilgi Eksikliği","Soruyu Anlayamama","Yorum Eksikliği"
  ];

  List classesTYT = [
    "Biyoloji",
    "Coğrafya",
    "Din",//AYT YOK
    //"Edebiyat",//TYT YOK
    "Felsefe",//AYT YOK
    "Fizik",
    "Geometri",
    "Kimya",
    "Matematik",
    "Tarih",
    "Türkçe",
  ];

  List classesAYT=[
    "Biyoloji",
    "Coğrafya",
    "Edebiyat",
    "Fizik",
    "Geometri",
    "Kimya",
    "Matematik",
    "Tarih",
    //"Türkçe",
  ];

  List turkceTYT = [
   "Sözcükte Anlam",
  "Cümlede Anlam",
  "Paragraf",
  "Yazım Kuralları",
  "Noktalama Kuralları",
  "Ses Bilgisi",
  "Sözcük Türleri",
  "Cümle Ögeleri",
  "Ekler",
  "Anlatım Bozukluğu",
  "Fiilde Çatı-Fiil"
  ];

  List matematikTYT = [
  "Temel Kavramlar",
  "Basamak Kavramı",
  "Bölme ve Bölünebilme",
  "EBOB – EKOK",
  "Rasyonel Sayılar",
  "Köklü İfadeler",
  "Üslü İfadeler",
  "Denklem Çözme",
  "Basit Eşitsizlikler",
  "Mutlak Değer",
  "Çarpanlara Ayırma",
  "Oran-Orantı",
  "Problemler",
  "Kümeler - Kartezyen Çarpım",
  "Fonksiyonlar",
  "Polinomlar",
  "İstatistik (Veri)",
  "Mantık",

  ];

  List matematikAYT = [
    "Temel Kavramlar",
    "Sayı Basamakları",
    "Bölme ve Bölünebilme",
    "EBOK-EKOK",
    "Rasyonel Sayılar",
    "Basit Eşitsizlikler",
    "Mutlak Değer",
    "Üslü Sayılar",
    "Köklü Sayılar",
    "Çarpanlara Ayırma",
    "Oran Orantı",
    "Kümeler ve Kartezyen Çarpım",
    "Mantık",
    "Fonksiyonlar",
    "Polinomlar",
    "2.Dereceden Denklemler",
    "Parabol",
    "Permütasyon-Kombinasyon-Olasılık–Binom",
    "Trigonometri",
    "Karmaşık Sayılar",
    "Logaritma",
    "Diziler",
    "Seriler",
    "Limit",
    "Türev",
    "İntegral",
  ];

  List biyolojiTYT = [
    "Yaşam Bilimi Biyoloji",
    "Canlıların Ortak Özellikleri",
    "Canlıların Temel Bileşenleri",
    "Hücre ve Organeller",
    "Canlıların Sınıflandırılması",
    "Hücre Bölünmeleri",
    "Kalıtım",
    "Ekoloji ve Çevre Sorunları",
  ];
  List kimyaTYT = [
    "Kimya Bilimi",
    "Atomun ve Periyodik Sistem",
    "Kimyasal Türler Arası Etkileşimler",
    "Kimyasal Hesaplamalar",
    "Kimyanın Temel Kanunları",
    "Asit, Baz ve Tuz",
    "Karışımlar",
    "Doğa ve Kimya",
  ];
  List dinTYT = [
    "Bilgi ve İnanç",
    "İbadetler",
    "Ahlak ve Değerler",
    "Hz. Muhammed'in Hayatı",
    "Vahiy ve Akıl",
    "İslam Düşüncesinde Yorumlar, Mezhepler",
  ];
  List geoTYT = [
    "Açılar ve Üçgenler",
    "Çokgenler ve Dörtgenler",
    "Çember ve Daire",
    "Katı Cisimler",
    "Analitik Geometri",
  ];

  List geoAYT = [
    "Doğruda ve Üçgende Açı",
    "Özel Üçgenler(Dik-İkiz-Eş)",
    "Açıortay ve Kenarortay",
    "Açı Kenar Bağıntıları",
    "Üçgende Alan ve Benzerlik",
    "Çokgenler",
    "Noktanın Analitiği",
    "Doğrunun Analitiği",
    "Dönüşüm Geometrisi",
    "Çember ve Daire",
    "Özel Dörtgenler",
    "Katı Cisimler",
    "Çemberin Analitiği",
  ];
  List bioAYT = [
    "Sinir Sistemi",
    "Endokrin Sistem",
    "Duyu Organları",
    "Destek ve Hareket Sistemi",
    "Sindirim Sistemi",
    "Dolaşım ve Bağışıklık Sistemi",
    "Solunum Sistemi",
    "Boşaltım Sistemi",
    "Üriner Sistem",
    "Üreme Sistemi ve Embriyonik Gelişim",
    "Komünite ve Popülasyon Ekolojisi",
    "Nükleik Asitler",
    "Genetik Şifre ve Protein Sentezi",
    "Canlılık ve Enerji",
    "Fotosentez ve Kemosentez",
    "Hücresel Solunum",
    "Bitki Biyolojisi",
    "Canlılar ve Çevre",
  ];
  List kimyaAYT = [
    "Kimya Bilimi",
    "Atom ve Yapısı",
    "Periyodik Sistem",
    "Kimyasal Türler Arası Etkileşim",
    "Kimyasal Hesaplamalar",
    "Modern Atom Teorisi",
    "Gazlar",
    "Çözeltiler",
    "Kimyasal Tepkimelerde Enerji",
    "Kimyasal Tepkimelerde Hız",
    "Kimyasal Tepkimelerde Denge",
    "Asit-Baz Dengesi",
    "Çözünürlük Dengesi",
    "Kimya ve Elektrik",
    "Organik Kimya",
  ];
  List fizikAYT = [
    "Vektörler",
    "Kuvvet, Tork ve Denge",
    "Kütle Merkezi",
    "Basit Makineler",
    "Hareket",
    "Newton’un Hareket Yasaları",
    "İş, Güç ve Enerji II",
    "Atışlar",
    "İtme ve Momentum",
    "Elektrik Alan ve Potansiyel",
    "Paralel Levhalar ve Sığa",
    "Manyetik Alan ve Manyetik Kuvvet",
    "İndüksiyon, Alternatif Akım ve Transformatörler",
    "Çembersel Hareket",
    "Kütle Çekim ve Kepler Yasaları",
    "Basit Harmonik Hareket",
    "Dalga Mekaniği ve Elektromanyetik Dalgalar",
    "Atom Modelleri",
    "Büyük Patlama ve Radyoaktivite",
    "Modern Fizik",
    "Modern Fiziğin Teknolojideki Uygulamaları",
  ];
  List tarihTYT = [
  "Tarih Bilimine Giriş",
  "İlk Türk Devletleri",
  "İslam Tarihi",
  "Türk-İslam Tarihi",
  "Osmanlı Devl. Kuruluşu",
  "Osmanlı Devl. Yükselme Dön.",
  "Yeniçağ’da Avrupa",
  "19. yy’da Osmanlı Devl.",
  "Osmanlı Kültür ve Medeniyeti",
  "20. yy’da Osmanlı Devleti",
  "1. Dünya Savaşı",
  "Kurtuluş Savaşı’na Hazırlık",
  "Mondros-İşgaller Ve Cemiyetler",
  "1.TBMM Dönemi",
  "Kurtuluş Savaşı",
  "Atatürk İlke Ve İnkılapları",
  "Dış Politika",

  ];
  List tarihAYT = [
    "Tarih Bilimi",
    "İlk Uygarlıklar",
    "İlk Türk Devletleri",
    "İslam Tarihi ve Medeniyeti",
    "İlk Türk İslam Devletleri",
    "Türkiye Tarihi",
    "Orta Çağ’da Avrupa",
    "Beylikten Devlete",
    "Dünya Gücü: Osmanlı Devleti",
    "Arayış Yılları",
    "Yeni ve Yakın Çağ’da Avrupa",
    "18.Yüzyıl Değişim ve Diploması",
    "En Uzun Yüzyıl",
    "Osmanlı Kültür ve Medeniyeti",
    "20.Yüzyıl Başlarında Osmanlı Devleti",
    "İnkılap Tarihi Tüm Konular",
    "20.Yüzyıl Başlarında Dünya",
    "Kurtuluş Savaşı",
    "Atatürk İlke ve İnkılapları",
    "İkinci Dünya Savaşı",
    "Soğuk Savaş Dönemi",
    "Yumuşama Dönemi",
    "Küreselleşen Dünya",
  ];
  List cografyaTYT = [
    "Doğa Ve İnsan",
    "Dünya’nın Şekli ve Hareketleri",
    "Coğrafi Konum",
    "Harita Bilgisi",
    "Atmosfer ve Sıcaklık",
    "İklim Bilgisi",
    "İç ve Dış Kuvvetler",
    "Nüfus ve Yerleşme",
    "Türkiye’nin Yer Şekilleri",
    "Ekonomik Faaliyetler",
    "Bölgeler",
    "Doğal Afetler"

  ];
  List cografyaAYT = [
    "Dünya’nın Şekli ve Hareketleri",
    "Coğrafi Konum",
    "Harita Bilgisi",
    "İç Kuvvetler",
    "Ekosistem",
    "İlk Medeniyet ve Şehirler",
    "Nüfus Politikaları",
    "Türkiye’de Nüfus ve Yerleşme",
    "Ekonomik Faaliyetler",
    "Göç ve Şehirleşme",
    "Türkiye Ekonomisi",
    "Türkiye’nin Jeopolitik Konumu",
    "Bölgesel Kalkınma Projeleri",
    "İklim ve Yer şekilleri",
    "Küresel ve Bölgesel Örgütler",
    "Ülkeler Arası Etkileşimler",
    "Üretim Alanları ve Ulaşım Ağları",
    "Bölgeler ve Ülkeler",
    "Çevre ve Toplum",
    "Doğal Afetler",
  ];
  List felsefeTYT = [
    "Felsefenin Alanı",
    "Bilgi Felsefesi",
    "Bilim Felsefesi",
    "Varlık Felsefesi",
    "Ahlak Felsefesi",
    "Siyaset Felsefesi",
    "Din Felsefesi",
    "Sanat Felsefesi",
  ];
  List edebiyatAYT = [
    "Anlam Bilgisi",
    "Dil Bilgisi",
    "Metinlerin Sınıflandırılması",
    "Şiir Bilgisi",
    "Edebi Sanatlar",
    "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi",
    "Halk Edebiyatı",
    "Divan Edebiyatı",
    "Tanzimat Edebiyatı",
    "Servet-İ Fünun Ve Fecr-İ Ati Edebiyatı",
    "Milli Edebiyat",
    "Cumhuriyet Dönemi Edebiyatı",
    "Edebiyat Akımları",
  ];
  List fizikTYT = [
    "Fizik Bilimine Giriş",
    "Madde Ve Özellikleri",
    "Kuvvet ve Hareket",
    "Isı ve Sıcaklık",
    "Basınç ve Kaldırma Kuvveti",
    "Elektrik ve Manyetizma",
    "Optik",
    "Dalgalar",
  ];
}
