class MyStrings {

  List mistakes=[
    "asdasd","dsadsa","sdasda",
    "asdasd","dsadsa","sdasda",
    "asdasd","dsadsa","sdasda",
    "asdasd","dsadsa","sdasda",
  ];

  List classesTYT = [
    "Biyoloji",
    "Coğrafya",
    "Din",//AYT YOK
    //"Edebiyat",//TYT YOK
    "Felsefe",//AYT YOK
    "Fizik",
    "Geometri",
    "Kimya",
    "Matematik",
    "Tarih",
    "Türkçe",
  ];

  List classesAYT=[
    "Biyoloji",
    "Coğrafya",
    "Edebiyat",
    "Fizik",
    "Geometri",
    "Kimya",
    "Matematik",
    "Tarih",
    //"Türkçe",
  ];

  List turkceTYT = [
    "Ses Bilgisi",
    "Dil Bilgisi",
    "Noktalama İşaretleri",
    "Yazım Kuralları",
    "Anlatım Bozuklukları",
    "Paragraf",
    "Cümlede Anlam",
    "Sözcükte Anlam",
  ];

  List matematikTYT = [
    "Basit Eşitsizlikler",
    "Bölünebilme Kuralları",
    "Çarpanlara Ayırma",
    "Denklem Çözme",
    "Fonksiyonlar",
    "İstatistik",
    "Köklü Sayılar",
    "Kümeler-Kartezyen Çarpım",
    "Mantık",
    "Mutlak Değer",
    "OBEB-OKEK",
    "Olasılık",
    "Oran-Orantı",
    "Permütasyon-Kombinasyon",
    "Polinomlar",
    "Problemler",
    "Rasyonel Sayılar",
    "Sayı Basamakları",
    "Temel Kavramlar",
    "Üslü Sayılar"
  ];

  List matematikAYT = [
    "Temel Kavramlar",
    "Sayı Basamakları",
    "Bölme ve Bölünebilme",
    "EBOK-EKOK",
    "Rasyonel Sayılar",
    "Basit Eşitsizlikler",
    "Mutlak Değer",
    "Üslü Sayılar",
    "Köklü Sayılar",
    "Çarpanlara Ayırma",
    "Oran Orantı",
    "Kümeler ve Kartezyen Çarpım",
    "Mantık",
    "Fonksiyonlar",
    "Polinomlar",
    "2.Dereceden Denklemler",
    "Parabol",
    "Permütasyon-Kombinasyon-Olasılık–Binom",
    "Trigonometri",
    "Karmaşık Sayılar",
    "Logaritma",
    "Diziler",
    "Seriler",
    "Limit",
    "Türev",
    "İntegral",
  ];

  List biyolojiTYT = [
    "Canlıların Ortak Özellikleri",
    "Canlıların Temel Bileşenleri",
    "Hücre ve Organelleri",
    "Madde Geçişleri",
    "Canlıların Sınıflandırılması",
    "Hücre Bölünmeleri ve Üreme",
    "Kalıtım",
    "Ekosistem Ekoloji",
    "Bitkiler Biyolojisi",
  ];
  List kimyaTYT = [
    "Kimya Bilimi",
    "Atomun Yapısı",
    "Periyodik Tablo",
    "Maddenin Halleri",
    "Kimyasal Türler Arası Etkileşimler",
    "Kimyasal Hesaplamalar",
    "Kimyanın Temel Kanunları",
    "Asit, Baz ve Tuz",
    "Karışımlar",
    "Kimya Her Yerde",
  ];
  List dinTYT = [
    "Bilgi ve İnanç",
    "İbadetler",
    "Ahlak ve Değerler",
    "Hz. Muhammed (S.A.V)",
    "Vahiy ve Akıl",
    "İslam Düşüncesinde Yorumlar, Mezhepler",
    "Din, Kültür ve Medeniyet",
  ];
  List geoTYT = [
    "Açılar ve Üçgenler",
    "Çokgenler",
    "Analitik Geometri",
    "Yamuk",
    "Eşkenar Dörtgen",
    "Kare",
    "Dikdörtgen",
    "Çember ve Daire",
    "Katı Cisimler",
  ];

  List geoAYT = [
    "Doğruda ve Üçgende Açı",
    "Özel Üçgenler(Dik-İkiz-Eş)",
    "Açıortay ve Kenarortay",
    "Açı Kenar Bağıntıları",
    "Üçgende Alan ve Benzerlik",
    "Çokgenler",
    "Noktanın Analitiği",
    "Doğrunun Analitiği",
    "Dönüşüm Geometrisi",
    "Çember ve Daire",
    "Özel Dörtgenler",
    "Katı Cisimler",
    "Çemberin Analitiği",
  ];
  List bioAYT = [
    "Sinir Sistemi",
    "Endokrin Sistem",
    "Duyu Organları",
    "Destek ve Hareket Sistemi",
    "Sindirim Sistemi",
    "Dolaşım ve Bağışıklık Sistemi",
    "Solunum Sistemi",
    "Boşaltım Sistemi",
    "Üriner Sistem",
    "Üreme Sistemi ve Embriyonik Gelişim",
    "Komünite ve Popülasyon Ekolojisi",
    "Nükleik Asitler",
    "Genetik Şifre ve Protein Sentezi",
    "Canlılık ve Enerji",
    "Fotosentez ve Kemosentez",
    "Hücresel Solunum",
    "Bitki Biyolojisi",
    "Canlılar ve Çevre",
  ];
  List kimyaAYT = [
    "Kimya Bilimi",
    "Atom ve Yapısı",
    "Periyodik Sistem",
    "Kimyasal Türler Arası Etkileşim",
    "Kimyasal Hesaplamalar",
    "Modern Atom Teorisi",
    "Gazlar",
    "Çözeltiler",
    "Kimyasal Tepkimelerde Enerji",
    "Kimyasal Tepkimelerde Hız",
    "Kimyasal Tepkimelerde Denge",
    "Asit-Baz Dengesi",
    "Çözünürlük Dengesi",
    "Kimya ve Elektrik",
    "Organik Kimya",
  ];
  List fizikAYT = [
    "Vektörler",
    "Kuvvet, Tork ve Denge",
    "Kütle Merkezi",
    "Basit Makineler",
    "Hareket",
    "Newton’un Hareket Yasaları",
    "İş, Güç ve Enerji II",
    "Atışlar",
    "İtme ve Momentum",
    "Elektrik Alan ve Potansiyel",
    "Paralel Levhalar ve Sığa",
    "Manyetik Alan ve Manyetik Kuvvet",
    "İndüksiyon, Alternatif Akım ve Transformatörler",
    "Çembersel Hareket",
    "Kütle Çekim ve Kepler Yasaları",
    "Basit Harmonik Hareket",
    "Dalga Mekaniği ve Elektromanyetik Dalgalar",
    "Atom Modelleri",
    "Büyük Patlama ve Radyoaktivite",
    "Modern Fizik",
    "Modern Fiziğin Teknolojideki Uygulamaları",
  ];
  List tarihTYT = [
    "Tarih Bilimine Giriş",
    "İlk Türk Devletleri",
    "İslam Tarihi",
    "Türk-İslam Tarihi",
    "Osmanlı Devletinin Kuruluşu",
    "Osmanlı Devletinin Yükselme Dönemi",
    "Yeniçağ’da Avrupa",
    "19. yy’da Osmanlı Devleti",
    "Osmanlı Kültür ve Medeniyeti",
    "20. yy’da Osmanlı Devleti",
    "1. Dünya Savaşı",
    "Kurtuluş Savaşı’na Hazırlık",
    "Mondros-İşgaller Ve Cemiyetler",
    "1. TBMM Dönemi",
    "Kurtuluş Savaşı",
    "Atatürk ilke Ve İnkılapları",
    "Dış Politika",
  ];
  List tarihAYT = [
    "Tarih Bilimi",
    "İlk Uygarlıklar",
    "İlk Türk Devletleri",
    "İslam Tarihi ve Medeniyeti",
    "İlk Türk İslam Devletleri",
    "Türkiye Tarihi",
    "Orta Çağ’da Avrupa",
    "Beylikten Devlete",
    "Dünya Gücü: Osmanlı Devleti",
    "Arayış Yılları",
    "Yeni ve Yakın Çağ’da Avrupa",
    "18.Yüzyıl Değişim ve Diploması",
    "En Uzun Yüzyıl",
    "Osmanlı Kültür ve Medeniyeti",
    "20.Yüzyıl Başlarında Osmanlı Devleti",
    "İnkılap Tarihi Tüm Konular",
    "20.Yüzyıl Başlarında Dünya",
    "Kurtuluş Savaşı",
    "Atatürk İlke ve İnkılapları",
    "İkinci Dünya Savaşı",
    "Soğuk Savaş Dönemi",
    "Yumuşama Dönemi",
    "Küreselleşen Dünya",
  ];
  List cografyaTYT = [
    "Doğa ve İnsan",
    "Dünya’nın Şekli ve Hareketleri",
    "Coğrafi Konum",
    "Harita Bilgisi",
    "Atmosfer ve Sıcaklık",
    "Basınç ve Rüzgarlar Nem",
    "İklimler",
    "Su – Toprak ve Bitkiler",
    "Yağış ve Buharlaşma",
    "İç Kuvvetler / Dış Kuvvetler",
    "Doğal Afetler",
    "Bölgeler",
    "Yerleşme",
    "Ekonomik Faaliyetler",
    "Göç",
    "Nüfus",
    "Türkiye’nin Yer Şekilleri",
    "Uluslararası Ulaşım Hatları",
    "Çevre ve Toplum",
  ];
  List cografyaAYT = [
    "Dünya’nın Şekli ve Hareketleri",
    "Coğrafi Konum",
    "Harita Bilgisi",
    "İç Kuvvetler",
    "Ekosistem",
    "İlk Medeniyet ve Şehirler",
    "Nüfus Politikaları",
    "Türkiye’de Nüfus ve Yerleşme",
    "Ekonomik Faaliyetler",
    "Göç ve Şehirleşme",
    "Türkiye Ekonomisi",
    "Türkiye’nin Jeopolitik Konumu",
    "Bölgesel Kalkınma Projeleri",
    "İklim ve Yer şekilleri",
    "Küresel ve Bölgesel Örgütler",
    "Ülkeler Arası Etkileşimler",
    "Üretim Alanları ve Ulaşım Ağları",
    "Bölgeler ve Ülkeler",
    "Çevre ve Toplum",
    "Doğal Afetler",
  ];
  List felsefeTYT = [
    "Felsefenin Alanı",
    "Bilgi Felsefesi",
    "Bilim Felsefesi",
    "Varlık Felsefesi",
    "Ahlak Felsefesi",
    "Siyaset Felsefesi",
    "Din Felsefesi",
    "Sanat Felsefesi",
  ];
  List edebiyatAYT = [
    "Anlam Bilgisi",
    "Dil Bilgisi",
    "Metinlerin Sınıflandırılması",
    "Şiir Bilgisi",
    "Edebi Sanatlar",
    "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi",
    "Halk Edebiyatı",
    "Divan Edebiyatı",
    "Tanzimat Edebiyatı",
    "Servet-İ Fünun Ve Fecr-İ Ati Edebiyatı",
    "Milli Edebiyat",
    "Cumhuriyet Dönemi Edebiyatı",
    "Edebiyat Akımları",
  ];
  List fizikTYT = [
    "Fizik Bilimine Giriş",
    "Madde Ve Özellikleri",
    "Sıvıların Kaldırma Kuvveti",
    "Basınç",
    "Isı, Sıcaklık ve Genleşme",
    "Hareket",
    "Dinamik",
    "İş, Güç  ve  Enerji",
    "Elektrostatik",
    "Elektrik Akımı",
    "Optik",
    "Manyetizma",
    "Dalgalar",
  ];
}
